# Generated by Django 6.0.2 on 2026-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('tds', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('water_level', models.FloatField()),
                ('refactor_index', models.FloatField()),
                ('quality_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
