# Generated by Django 6.0.2 on 2026-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0002_waterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterreading',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
